package hpms.bs.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;



@ExtensionAttribute(disable=true)
@Table(name = "HPMS_DATA_PRIVILIAGE")
public class DataPriviliage extends BaseDTO {
     @Id
     @GeneratedValue
      private Long priviliageId;

      private Long companyId;

      private Long projectId;

      private Long userId;

      private Long roleId;

      private Long programId;

      private Long requestId;

    @Transient
    private String companyFullName;
    @Transient
    private String projectName;
    @Transient
    private String roleName;
    @Transient
    private String userName;

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public void setPriviliageId(Long priviliageId){
         this.priviliageId = priviliageId;
     }

     public Long getPriviliageId(){
         return priviliageId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setProjectId(Long projectId){
         this.projectId = projectId;
     }

     public Long getProjectId(){
         return projectId;
     }

     public void setUserId(Long userId){
         this.userId = userId;
     }

     public Long getUserId(){
         return userId;
     }

     public void setRoleId(Long roleId){
         this.roleId = roleId;
     }

     public Long getRoleId(){
         return roleId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
