package hpms.mdm.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HPMS_MDM_FEE")
public class Fee extends BaseDTO {
    @Id
    @GeneratedValue
    private Long feeId;

    private String feeCode;

    private String feeName;

    private String description;

    private String billingFrequency;

    private String billingMethod;

    private String revenueAccount;

    private Date startDateActive;

    private Date endDateActive;

    private String enableFlag;

    private Long feeTypeId;

    private String transType;

    private Long overdueRate;

    private Long chargeDays;

    private String roundRule;

    private Long precision;

    private String priceEditFlag;

    private String equipmentFlag;

    private String equipmentType;

    private String overdueFalg;

    private String itemFlag;


    public void setFeeId(Long feeId) {
        this.feeId = feeId;
    }

    public Long getFeeId() {
        return feeId;
    }

    public void setFeeCode(String feeCode) {
        this.feeCode = feeCode;
    }

    public String getFeeCode() {
        return feeCode;
    }

    public void setFeeName(String feeName) {
        this.feeName = feeName;
    }

    public String getFeeName() {
        return feeName;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setBillingFrequency(String billingFrequency) {
        this.billingFrequency = billingFrequency;
    }

    public String getBillingFrequency() {
        return billingFrequency;
    }

    public void setBillingMethod(String billingMethod) {
        this.billingMethod = billingMethod;
    }

    public String getBillingMethod() {
        return billingMethod;
    }

    public void setRevenueAccount(String revenueAccount) {
        this.revenueAccount = revenueAccount;
    }

    public String getRevenueAccount() {
        return revenueAccount;
    }

    public void setStartDateActive(Date startDateActive) {
        this.startDateActive = startDateActive;
    }

    public Date getStartDateActive() {
        return startDateActive;
    }

    public void setEndDateActive(Date endDateActive) {
        this.endDateActive = endDateActive;
    }

    public Date getEndDateActive() {
        return endDateActive;
    }

    public void setEnableFlag(String enableFlag) {
        this.enableFlag = enableFlag;
    }

    public String getEnableFlag() {
        return enableFlag;
    }

    public void setFeeTypeId(Long feeTypeId) {
        this.feeTypeId = feeTypeId;
    }

    public Long getFeeTypeId() {
        return feeTypeId;
    }

    public void setTransType(String transType) {
        this.transType = transType;
    }

    public String getTransType() {
        return transType;
    }

    public void setOverdueRate(Long overdueRate) {
        this.overdueRate = overdueRate;
    }

    public Long getOverdueRate() {
        return overdueRate;
    }

    public void setChargeDays(Long chargeDays) {
        this.chargeDays = chargeDays;
    }

    public Long getChargeDays() {
        return chargeDays;
    }

    public void setRoundRule(String roundRule) {
        this.roundRule = roundRule;
    }

    public String getRoundRule() {
        return roundRule;
    }

    public void setPrecision(Long precision) {
        this.precision = precision;
    }

    public Long getPrecision() {
        return precision;
    }

    public void setPriceEditFlag(String priceEditFlag) {
        this.priceEditFlag = priceEditFlag;
    }

    public String getPriceEditFlag() {
        return priceEditFlag;
    }

    public void setEquipmentFlag(String equipmentFlag) {
        this.equipmentFlag = equipmentFlag;
    }

    public String getEquipmentFlag() {
        return equipmentFlag;
    }

    public void setEquipmentType(String equipmentType) {
        this.equipmentType = equipmentType;
    }

    public String getEquipmentType() {
        return equipmentType;
    }

    public void setOverdueFalg(String overdueFalg) {
        this.overdueFalg = overdueFalg;
    }

    public String getOverdueFalg() {
        return overdueFalg;
    }

    public void setItemFlag(String itemFlag) {
        this.itemFlag = itemFlag;
    }

    public String getItemFlag() {
        return itemFlag;
    }

}
