package hpms.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HPMS_MDM_FEE_TYPE")
public class FeeType extends BaseDTO {
     @Id
     @GeneratedValue
      private Long feeTypeId;

      private String feeTypeCode;

      private String feeTypeName;

      private String description;

      private Date startDateActive;

      private Date endDateActive;

      private String enableFlag;


     public void setFeeTypeId(Long feeTypeId){
         this.feeTypeId = feeTypeId;
     }

     public Long getFeeTypeId(){
         return feeTypeId;
     }

     public void setFeeTypeCode(String feeTypeCode){
         this.feeTypeCode = feeTypeCode;
     }

     public String getFeeTypeCode(){
         return feeTypeCode;
     }

     public void setFeeTypeName(String feeTypeName){
         this.feeTypeName = feeTypeName;
     }

     public String getFeeTypeName(){
         return feeTypeName;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setStartDateActive(Date startDateActive){
         this.startDateActive = startDateActive;
     }

     public Date getStartDateActive(){
         return startDateActive;
     }

     public void setEndDateActive(Date endDateActive){
         this.endDateActive = endDateActive;
     }

     public Date getEndDateActive(){
         return endDateActive;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     }
