package hpms.mdm.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "HPMS_MDM_PROJECT")
public class Project extends BaseDTO {
     @Id
     @GeneratedValue
      private Long projectId;

      private String projectCode;

      private String projectName;

      private Long groupId;

      private Long companyId;

      private String projectContact;

      private String contactPhone;

      private String projectAddress;

      private Date startDateActive;

      private Date endDateActive;

      private String enableFlag;

      private Long programId;

      private Long requestId;


     public void setProjectId(Long projectId){
         this.projectId = projectId;
     }

     public Long getProjectId(){
         return projectId;
     }

     public void setProjectCode(String projectCode){
         this.projectCode = projectCode;
     }

     public String getProjectCode(){
         return projectCode;
     }

     public void setProjectName(String projectName){
         this.projectName = projectName;
     }

     public String getProjectName(){
         return projectName;
     }

     public void setGroupId(Long groupId){
         this.groupId = groupId;
     }

     public Long getGroupId(){
         return groupId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setProjectContact(String projectContact){
         this.projectContact = projectContact;
     }

     public String getProjectContact(){
         return projectContact;
     }

     public void setContactPhone(String contactPhone){
         this.contactPhone = contactPhone;
     }

     public String getContactPhone(){
         return contactPhone;
     }

     public void setProjectAddress(String projectAddress){
         this.projectAddress = projectAddress;
     }

     public String getProjectAddress(){
         return projectAddress;
     }

     public void setStartDateActive(Date startDateActive){
         this.startDateActive = startDateActive;
     }

     public Date getStartDateActive(){
         return startDateActive;
     }

     public void setEndDateActive(Date endDateActive){
         this.endDateActive = endDateActive;
     }

     public Date getEndDateActive(){
         return endDateActive;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
