package hpms.fin.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HPMS_FIN_METER_READ_HIS")
public class CusMeterReadHis extends BaseDTO {
    @Id
    @GeneratedValue
    private Long readHisId;

    private Long companyId;

    private Long projectId;

    private Long equipmentId;

    private String invoiceCode;

    private Float lastRead;

    private Float currentRead;

    private Float meterTotalUse;

    private Float meterTotalAmount;

    private Date readDate;

    private String flag;

    private String newRecordFlag;

    private String isPostedFlag;

    private String status;

    private Long programId;

    private Long requestId;
    private Long propertyId;

    @Transient
    private String companyFullName;
    @Transient
    private String projectName;
    @Transient
    private String equipmentName;
    @Transient
    private String statusDesc;
    @Transient
    private Long equipmentTypeId;
    @Transient
    private String propertyName;
    @Transient
    private Long structureId;
    @Transient
    private String typeName;

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Long getStructureId() {
        return structureId;
    }

    public void setStructureId(Long structureId) {
        this.structureId = structureId;
    }

    public Long getPropertyId() {
        return propertyId;
    }

    public void setPropertyId(Long propertyId) {
        this.propertyId = propertyId;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getEquipmentName() {
        return equipmentName;
    }

    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName;
    }

    public String getStatusDesc() {
        return statusDesc;
    }

    public void setStatusDesc(String statusDesc) {
        this.statusDesc = statusDesc;
    }

    public Long getEquipmentTypeId() {
        return equipmentTypeId;
    }

    public void setEquipmentTypeId(Long equipmentTypeId) {
        this.equipmentTypeId = equipmentTypeId;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    @Transient

    private String year;
    @Transient
    private String month;


    public void setReadHisId(Long readHisId) {
        this.readHisId = readHisId;
    }

    public Long getReadHisId() {
        return readHisId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setEquipmentId(Long equipmentId) {
        this.equipmentId = equipmentId;
    }

    public Long getEquipmentId() {
        return equipmentId;
    }

    public void setInvoiceCode(String invoiceCode) {
        this.invoiceCode = invoiceCode;
    }

    public String getInvoiceCode() {
        return invoiceCode;
    }

    public void setLastRead(Float lastRead) {
        this.lastRead = lastRead;
    }

    public Float getLastRead() {
        return lastRead;
    }

    public void setCurrentRead(Float currentRead) {
        this.currentRead = currentRead;
    }

    public Float getCurrentRead() {
        return currentRead;
    }

    public void setMeterTotalUse(Float meterTotalUse) {
        this.meterTotalUse = meterTotalUse;
    }

    public Float getMeterTotalUse() {
        return meterTotalUse;
    }

    public void setMeterTotalAmount(Float meterTotalAmount) {
        this.meterTotalAmount = meterTotalAmount;
    }

    public Float getMeterTotalAmount() {
        return meterTotalAmount;
    }

    public void setReadDate(Date readDate) {
        this.readDate = readDate;
    }

    public Date getReadDate() {
        return readDate;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getFlag() {
        return flag;
    }

    public void setNewRecordFlag(String newRecordFlag) {
        this.newRecordFlag = newRecordFlag;
    }

    public String getNewRecordFlag() {
        return newRecordFlag;
    }

    public void setIsPostedFlag(String isPostedFlag) {
        this.isPostedFlag = isPostedFlag;
    }

    public String getIsPostedFlag() {
        return isPostedFlag;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setProgramId(Long programId) {
        this.programId = programId;
    }

    public Long getProgramId() {
        return programId;
    }

    public void setRequestId(Long requestId) {
        this.requestId = requestId;
    }

    public Long getRequestId() {
        return requestId;
    }

}
