package hpms.fin.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HPMS_FIN_CUSMETER_BIND")
public class CusmeterBind extends BaseDTO {
     @Id
     @GeneratedValue
      private Long cusmeterBindId;

      private Long propertyId;

      private Long equipmentId;

      private Long programId;

      private Long requestId;

    @Transient
    private String companyFullName;
    @Transient
    private String projectName;
    @Transient
    private String equipmentName;
    @Transient
    private String equipmentCode;
    @Transient
    private String propertyName;
    @Transient
    private Long equipmentTypeId;

    public Long getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    @Transient
    private Long companyId;
    @Transient
    private Long projectId;

    public Long getEquipmentTypeId() {
        return equipmentTypeId;
    }

    public void setEquipmentTypeId(Long equipmentTypeId) {
        this.equipmentTypeId = equipmentTypeId;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getEquipmentName() {
        return equipmentName;
    }

    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName;
    }

    public String getEquipmentCode() {
        return equipmentCode;
    }

    public void setEquipmentCode(String equipmentCode) {
        this.equipmentCode = equipmentCode;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    public void setCusmeterBindId(Long cusmeterBindId){
         this.cusmeterBindId = cusmeterBindId;
     }

     public Long getCusmeterBindId(){
         return cusmeterBindId;
     }

     public void setPropertyId(Long propertyId){
         this.propertyId = propertyId;
     }

     public Long getPropertyId(){
         return propertyId;
     }

     public void setEquipmentId(Long equipmentId){
         this.equipmentId = equipmentId;
     }

     public Long getEquipmentId(){
         return equipmentId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
