package hpms.fin.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;

@ExtensionAttribute(disable=true)
@Table(name = "HPMS_FIN_INVOICE_LINE")
public class InvoiceLine extends BaseDTO {
     @Id
     @Column
     @GeneratedValue
      private Long invoiceLineId;
      @Column
      private Long invoiceId;
      @Column
      private Long lineNumner;
      @Column
      private Long feeId;
      @Column
      private String accountNum;
      @Column
      private String costCenter;
      @Column
      private String profitCenter;
      @Column
      private Long lineAmount;
      @Column
      private String taxCode;
      @Column
      private Long taxAmount;
      @Column
      private String description;
      @Column
      private Long programId;
      @Column
      private Long requestId;

     @Transient
     private String feeName;
     @Transient
     private Invoice invoice;

    public Invoice getInvoice() {
        return invoice;
    }

    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }

    public String getFeeName() {
        return feeName;
    }

    public void setFeeName(String feeName) {
        this.feeName = feeName;
    }

     public void setInvoiceLineId(Long invoiceLineId){
         this.invoiceLineId = invoiceLineId;
     }

     public Long getInvoiceLineId(){
         return invoiceLineId;
     }

     public void setInvoiceId(Long invoiceId){
         this.invoiceId = invoiceId;
     }

     public Long getInvoiceId(){
         return invoiceId;
     }

     public void setLineNumner(Long lineNumner){
         this.lineNumner = lineNumner;
     }

     public Long getLineNumner(){
         return lineNumner;
     }

     public void setFeeId(Long feeId){
         this.feeId = feeId;
     }

     public Long getFeeId(){
         return feeId;
     }

     public void setAccountNum(String accountNum){
         this.accountNum = accountNum;
     }

     public String getAccountNum(){
         return accountNum;
     }

     public void setCostCenter(String costCenter){
         this.costCenter = costCenter;
     }

     public String getCostCenter(){
         return costCenter;
     }

     public void setProfitCenter(String profitCenter){
         this.profitCenter = profitCenter;
     }

     public String getProfitCenter(){
         return profitCenter;
     }

     public void setLineAmount(Long lineAmount){
         this.lineAmount = lineAmount;
     }

     public Long getLineAmount(){
         return lineAmount;
     }

     public void setTaxCode(String taxCode){
         this.taxCode = taxCode;
     }

     public String getTaxCode(){
         return taxCode;
     }

     public void setTaxAmount(Long taxAmount){
         this.taxAmount = taxAmount;
     }

     public Long getTaxAmount(){
         return taxAmount;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
