package hpms.fin.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.*;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HPMS_FIN_INVOICE")
public class Invoice extends BaseDTO {
     @Id
     @Column
     @GeneratedValue
      private Long invoiceId;
      @Column
      private Long companyId;
      @Column
      private Long projectId;
      @Column
      private String payableCode;
      @Column
      private String invoiceType;
      @Column
      private Date invoiceDate;
      @Column
      private String invoiceNum;
      @Column
      private Long occupationId;
      @Column
      private Date accountDate;
      @Column
      private String accountPeriod;
      @Column
      private Long paymentTermId;
      @Column
      private Long paymentMethodId;
      @Column
      private String transType;
      @Column
      private Float invoiceAmount;
      @Column
      private Float taxAmount;
      @Column
      private String enableFlag;
      @Column
      private Long programId;
      @Column
      private Long requestId;

    @Transient
    private String companyFullName;
    @Transient
    private String paymentTermName;
    @Transient
    private String projectName;
    @Transient
    private String propertyNumber;
    @Transient
    private String propertyName;
    @Transient
    private String customerName;
    @Transient
    private String balance;
    @Transient
    private String paymentMethodName;
    @Transient
    private Long structureId;
    @Transient
    private String meaning1;
    @Transient
    private String meaning2;

    public String getMeaning1() {
        return meaning1;
    }

    public void setMeaning1(String meaning1) {
        this.meaning1 = meaning1;
    }

    public String getMeaning2() {
        return meaning2;
    }

    public void setMeaning2(String meaning2) {
        this.meaning2 = meaning2;
    }

    public Long getStructureId() {
        return structureId;
    }

    public void setStructureId(Long structureId) {
        this.structureId = structureId;
    }

    public String getCompanyFullName() {
        return companyFullName;
    }

    public void setCompanyFullName(String companyFullName) {
        this.companyFullName = companyFullName;
    }
    public String getBalance() {
        return balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }
    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    public String getPropertyNumber() {
        return propertyNumber;
    }

    public void setPropertyNumber(String propertyNumber) {
        this.propertyNumber = propertyNumber;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getPaymentTermName() {
        return paymentTermName;
    }

    public void setPaymentTermName(String paymentTermName) {
        this.paymentTermName = paymentTermName;
    }

    public String getPaymentMethodName() {
        return paymentMethodName;
    }

    public void setPaymentMethodName(String paymentMethodName) {
        this.paymentMethodName = paymentMethodName;
    }

    public void setInvoiceId(Long invoiceId){
         this.invoiceId = invoiceId;
     }

     public Long getInvoiceId(){
         return invoiceId;
     }

     public void setCompanyId(Long companyId){
         this.companyId = companyId;
     }

     public Long getCompanyId(){
         return companyId;
     }

     public void setProjectId(Long projectId){
         this.projectId = projectId;
     }

     public Long getProjectId(){
         return projectId;
     }

     public void setPayableCode(String payableCode){
         this.payableCode = payableCode;
     }

     public String getPayableCode(){
         return payableCode;
     }

     public void setInvoiceType(String invoiceType){
         this.invoiceType = invoiceType;
     }

     public String getInvoiceType(){
         return invoiceType;
     }

     public void setInvoiceDate(Date invoiceDate){
         this.invoiceDate = invoiceDate;
     }

     public Date getInvoiceDate(){
         return invoiceDate;
     }

     public void setInvoiceNum(String invoiceNum){
         this.invoiceNum = invoiceNum;
     }

     public String getInvoiceNum(){
         return invoiceNum;
     }

     public void setOccupationId(Long occupationId){
         this.occupationId = occupationId;
     }

     public Long getOccupationId(){
         return occupationId;
     }

     public void setAccountDate(Date accountDate){
         this.accountDate = accountDate;
     }

     public Date getAccountDate(){
         return accountDate;
     }

     public void setAccountPeriod(String accountPeriod){
         this.accountPeriod = accountPeriod;
     }

     public String getAccountPeriod(){
         return accountPeriod;
     }

     public void setPaymentTermId(Long paymentTermId){
         this.paymentTermId = paymentTermId;
     }

     public Long getPaymentTermId(){
         return paymentTermId;
     }

     public void setPaymentMethodId(Long paymentMethodId){
         this.paymentMethodId = paymentMethodId;
     }

     public Long getPaymentMethodId(){
         return paymentMethodId;
     }

     public void setTransType(String transType){
         this.transType = transType;
     }

     public String getTransType(){
         return transType;
     }

     public void setInvoiceAmount(Float invoiceAmount){
         this.invoiceAmount = invoiceAmount;
     }

     public Float getInvoiceAmount(){
         return invoiceAmount;
     }

     public void setTaxAmount(Float taxAmount){
         this.taxAmount = taxAmount;
     }

     public Float getTaxAmount(){
         return taxAmount;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     }
